from django.urls import path
from .views import *

urlpatterns = [
    path('create_company/', create_company),
    path('create_region/', create_region),
    path('create_subregion/', create_subregion),
    path('create_city/', create_city),
    path('create_store/', create_store),
    path('create_department/', create_department),
    path('create_category/', create_category),
    path('create_subcategory/', create_subcategory),
    path('create_product/', create_product),
    path('get_company_by_id/', get_company_by_id),
    path('get_region_by_id/', get_region_by_id),
    path('get_subregion_by_id/', get_subregion_by_id),
    path('get_city_by_id/', get_city_by_id),
    path('get_store_by_id/', get_store_by_id),
    path('get_department_by_id/', get_department_by_id),
    path('get_category_by_id/', get_category_by_id),
    path('get_subcategory_by_id/', get_subcategory_by_id),
    path('get_product_by_id/', get_product_by_id),
    path('get_department_by_store_id/', get_department_by_store_id),
    path('get_category_by_store_id/', get_category_by_store_id),
    path('get_subcategory_by_store_id/', get_subcategory_by_store_id),
    path('get_product_by_store_id/', get_product_by_store_id),
    path('get_category_by_department_id/', get_category_by_department_id),
    path('get_subcategory_by_category_id/', get_subcategory_by_category_id),
    path('get_product_by_subcategory_id/', get_product_by_subcategory_id),
    path('get_all_company/', get_all_company),
    path('get_all_region/', get_all_region),
    path('get_all_subregion/', get_all_subregion),
    path('get_all_city/', get_all_city),
    path('get_all_store/', get_all_store),
    path('get_all_department/', get_all_department),
    path('get_all_category/', get_all_category),
    path('get_all_subcategory/', get_all_subcategory),
    path('get_all_product/', get_all_product),
    path('delete_store_by_id/', delete_store_by_id),
    # path('delete_category_by_cat_id/', delete_category_by_cat_id),
    # path('download_image_by_store_id/', download_image_by_store_id),
    path('update_company_by_id/', update_company_by_id),
    path('update_store_by_id/', update_store_by_id),
    path('update_department_by_id/', update_department_by_id),
    path('update_category_by_id/', update_category_by_id),
    path('update_subcategory_by_id/', update_subcategory_by_id),
    path('update_product_by_id/', update_product_by_id),
    # path('department_update_or_create_by_id/', department_update_or_create_by_id),
    path('add_follower_to_the_store/', add_follower_to_the_store),
    path('get_followers_by_store/', get_followers_by_store),
    path('get_stores_by_follower/', get_stores_by_follower),
    path('remove_follower_from_the_store/', remove_follower_from_the_store),

] 
