# Generated by Django 2.2.7 on 2019-12-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newuser', '0002_sellersprofile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
